fix: path

diff --git a/.github/workflows/push_to_ecr.yaml b/.github/workflows/push_to_ecr.yaml
--- a/.github/workflows/push_to_ecr.yaml
+++ b/.github/workflows/push_to_ecr.yaml
@@ -39,11 +39,15 @@ jobs:
 
       - name: Extract ECR Repository URL
         id: get_ecr_url
+        working-directory: infra
         run: |
-          cd infra
-          ECR_URL=$(terraform output -raw ecr_repository_url)
-          echo "Extracted ECR_URL: $ECR_URL"
+          ECR_URL=$(terraform output -raw ecr_repository_url 2>/dev/null)
+          if [[ -z "$ECR_URL" ]]; then
+            echo "Terraform output is empty or failed"
+            exit 1
+          fi
           echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV
+      
 
       - name: Log in to Amazon ECR
         uses: aws-actions/amazon-ecr-login@v1
